### ISSUE TITLE
LINK DOWN

### ISSUE THREAD

**Issue by KonSparrow92** [fawyrad/Premium-OTT#1]
Link yang anda beri sudah down. Harap maklum. terima kasih

**Comment by fawyrad** [comment]
Account Astro kena blocked 🤣 Akan fix dalam beberapa jam lagi.

**Comment by fawyrad** [comment]
> Link yang anda beri sudah down. Harap maklum. terima kasih

Done fixed. Dah ganti account baru. Boleh teruskan guna link MPD yg sama.
