### ISSUE TITLE
Channel 805

### ISSUE THREAD

**Issue by fawyrad** [fawyrad/Premium-OTT#4]
**EStreamingMissingStreamType: 2070-CONTENT_BLOCKED_DEVICETYPE**

Buat masa ni, Astro Go blocked device yang tak eligible untuk generate token channel UHD seperti 805. Bukan link saya tengah down ye.

**Comment by mdferin** [comment]
Bukan BUG.tapi  xtro dah patch
nak gen .pastikan guna account MultiRoom

**Comment by fawyrad** [comment]
> Bukan BUG.tapi xtro dah patch nak gen .pastikan guna account MultiRoom

Sayang lak nak guna account Multiroom, stock tak unlimited macam account Astro Go. Takpelah, nasib link Astro Sports UHD Sooka masih hidup.
