### ISSUE TITLE
Url Dead

### ISSUE THREAD

**Issue by mdferin** [fawyrad/Premium-OTT#6]
Update Boss
url semua dah error

**Comment by fawyrad** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/1d0db7e1-c759-4b3c-9dd3-34ad383dddb9)

Haha, account AWS dah suspended. Account beli tu, akan diganti link bila ada akaun AWS baru.

**Comment by cheehong618** [comment]
hari ni dpt ganti x link baru?

**Comment by cheehong618** [comment]
ok,sbb nak tgk channel aod tu setiap hari isnin-jumaat mlm sbb ada episode baru live channel tu,kalau skrg ni xdpt ganti xpalah

**Comment by mdferin** [comment]
> > hari ni dpt ganti x link baru?
> 
> Script auto renew token Astro saya buat tu based on lambda function dalam AWS. Since akaun Amazon AWS dah suspended, script takleh running. So untuk ganti link baru tu memerlukan akaun AWS baru, malas nak guna vps macam DO sebab kena jaga monthly commitment berbanding AWS ada free tier.

kenapa tak buat version based worker di cloudflare ?
rasanya ok ja tak ada masalah

**Comment by cheehong618** [comment]
sooka dah xda,sudah tolak channel tu

**Comment by fawyrad** [comment]
> sooka dah xda,sudah tolak channel tu

Dah update new link. Enjoy.
