### ISSUE TITLE
Prima problem

### ISSUE THREAD

**Issue by AnarkiGadget** [fawyrad/Premium-OTT#7]
Prima video glitch

**Comment by fawyrad** [comment]
> Prima video glitch

Link saya hanya redirect ke link asal generated by Astro Go: http://linears-playback.astro.com.my/vsg/41i3ZavjNLNR9Cw2TlO57sjwmibrO8ztXKwD3HNQ-z7pA=PjbV/dash-wv/jitp-linearwm/1000/default_primary.mpd

So kalau berlaku delay, glitch dll semua dari server asal Astro. On more thing, 3hb esok channel PRIMA akan merge content channel WARNA. Maybe sebab tu ada video glitch. Saya sendiri try stream channel PRIMA sekarang takde isu.
